#index:
#    path: /
#    controller: App\Controller\DefaultController::index

fake_insert:
  path: /fake/insert
  controller: App\Controller\FakeController::insert

fake_detail:
  path: /fake/detail/{id}
  controller: App\Controller\FakeController::detail
